snyk-sast:
  image: node:latest
  when: manual
  variables:
    SNYK_CLIENT_ID: ${SNYK_CLIENT_ID}
    SNYK_CLIENT_SECRET: ${SNYK_CLIENT_SECRET}
    SNYK_ORG_ID: ${SNYK_ORG_ID}

  script:
    - npm install -g snyk
    - snyk auth --org="${SNYK_ORG_ID}" --client-id="${SNYK_CLIENT_ID}" --client-secret="${SNYK_CLIENT_SECRET}"
    - snyk code test --org=${SNYK_ORG_ID} --sarif --sarif-file-output=snyk_sast.sarif

  artifacts:
    reports:
      sast: snyk_sast.sarif
