name: Snyk SAST HTML Report
on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  Snyk-SAST-Scan-HTML-Report:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
      - name: install snyk
        run: npm install -g snyk
      - name: install snyk-to-html
        run: npm install -g snyk-to-html
      - name: Configure environment
        run: snyk config environment SNYK-GOV-01
      - name: Authenticate with Snyk SaaS
        run: snyk auth --org="${{ secrets.SNYK_ORG_ID }}" --client-id="${{ secrets.SNYK_CLIENT_ID }}" --client-secret="${{ secrets.SNYK_CLIENT_SECRET }}"
      - name: Run SAST
        run: snyk code test --org="${{ secrets.SNYK_ORG_ID }}"  --json | snyk-to-html -o ${{ github.head_ref || github.ref_name }}_sast_report.html
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.head_ref || github.ref_name }}_sast_report.html
          path: ${{ github.head_ref || github.ref_name }}_sast_report.html


